export default configurationData = {
  projects: [
    {
      title: 'Test',
      date: '14. 2. 2014',
      description: 'Toto je pouze test, autodestrukce mobilu za 3, 2, 1 .',
      points: [
        {
          title: 'Test1',
          b: 50.000000000,      // store 9 decimals to keep mm precision
          l: 14.000000000,
          h: 100.000,           // 3 is enough for heights
          x: 1048448.751,
          y: 774041.352,
          z: 54.368,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          hdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
          fix: 'rtk-fix',
        }, {
          title: 'Test2',
          b: 51.000000000,
          l: 15.000000000,
          h: 101.000,
          x: 947833.858,
          y: 688702.591,
          z: 58.421,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          hdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
          fix: 'rtk-fix',
        }, {
          title: 'Test3',
          b: 49.000000000,
          l: 15.000000000,
          h: 101.000,
          x: 1168433.345,
          y: 717321.474,
          z: 58.874,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          hdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
          fix: 'rtk-fix',
        },
      ],
      pointCount: 3,
    }, {
      title: 'Placing Test',
      date: '13.11.2024',
      description: 'Obsahuje bod na testovani blizsiho vytyceni.',
      points: [
        {
          title: 'Test',
          b: 50.000000000,      // untransformed
          l: 14.000000000,      // untransformed
          h: 100.000,           // untransformed
          x: 1128950.000,
          y: 590010.000,
          z: 345.000,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          hdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
          fix: 'rtk-fix',
        }, {
          title: 'Test2',
          b: 50.000000000,      // untransformed
          l: 14.000000000,      // untransformed
          h: 100.000,           // untransformed
          x: 1128952.000,
          y: 590009.000,
          z: 346.346,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          hdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
          fix: 'rtk-fix',
        },
      ],
      pointCount: 2,
    },
  ],
  codes: null,
  ntripSettings: {
    ntripIp: '195.245.209.181',
    ntripPort: '2101',
    ntripUsername: 'cvutvyuka',
    ntripPassword: 'k155dremejakokone',
    selectedMntp: null,
    mountpoints: [],
    ntripConnect: false,
    clientWrapper: null,
  },
  pointSettings: {
    title: '1',
    x: '',
    y: '',
    z: '',
    b: '',
    l: '',
    h: '',
    accuB: 0,
    accuL: 0,
    accuH: 0,
    pdop: 0,
    hdop: 0,
    time: 0,
    date: 0,
    height: 0,
    offset: 0,
    code: '',
  },
  projectSettings: {
    title: '',
    projectId: null,
    date: '',
    description: '',
    projectPointCount: '',
    points: [],
    showFlatList: false,
    showPointFlatList: false,
    showCreateProject: false,
    showCreatePoint: false,
    showExportModal: false,
    showImportModal: false,
    showStaticPoints: false,
  },
  connectionSettings: {
    isEnabled: true,
    isConnected: false,
    connectedDeviceClassic: null,
    hostIP: '',
    hostPort: '8080',
    // Handed to the receiver over Bluetooth so it can join the phone hotspot
    hotspotSsid: '',
    hotspotPassword: '',
  },
  measurementSettings: {
    nazev: '1',
    etrs: {
      b: 0,
      l: 0,
      h: 0,
    },
    jtsk: {
      X: 0,
      Y: 0,
      Hbpv: 0,
    },
    coordPDOP: 0,
    coorHDOP: 0,
    coordAccuX: 0,
    coordAccuY: 0,
    coordAccuZ: 0,
    sumCoordB: 0,
    sumCoordL: 0,
    sumCoordH: 0,
    coordMeasuredTime: 0,
    boolRtk: false,
    boolRaw: false,
    formattedTime: '00:00:00',
    epochCount: 0,
    count:0,
    startTime: null,
    endTime: null,
    intervalRawMeasurement: 0,
    fix: '',
  },
  placingSettings: {
    points: null,
    selectedPoint: -1,
    dist: 0,
    heading: 0,
    heightDelta: 0,
    deltaY: 0,
    deltaX: 0,
  },
  nmeaRead: [],
  rtcmNtrip: [],
  lastGGA: '',
}