export default configurationData = {
  projects: [
    {
      title: 'Test',
      date: '14.2.2014',
      description: 'Toto je pouze test, autodestrukce mobilu za 3, 2, 1 .',
      points: [
        {
          title: 'Test1',
          b: 50,
          l: 14,
          h: 100,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
        }, {
          title: 'Test2',
          b: 51,
          l: 15,
          h: 101,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
        }, {
          title: 'Test3',
          b: 49,
          l: 15,
          h: 101,
          accuB: 0,
          accuL: 0,
          accuH: 0,
          pdop: 0,
          time: 0,
          date: 0,
          height: 0,
          offset: 0,
          code: 'test',
        },
      ],
    },
  ],
  codes: null,
  ntripSettings: {
    ntripIp: '195.245.209.181',
    ntripPort: '2101',
    ntripUsername: 'cvutvyuka',
    ntripPassword: 'k155dremejakokone',
    selectedMntp: null,
    mountpoints: [],
    ntripConnect: false,
    clientWrapper: null,
  },
  pointSettings: {
    title: '1',
    b: 0,
    l: 0,
    h: 0,
    accuB: 0,
    accuL: 0,
    accuH: 0,
    pdop: 0,
    time: 0,
    date: 0,
    height: 0,
    offset: 0,
    code: '',
  },
  projectSettings: {
    title: '',
    projectId: 0,
    date: '',
    description: '',
    projectPointCount: '',
    points: [],
    showFlatList: false,
    showPointFlatList: false,
    showCreateProject: false,
    showCreatePoint: false,
  },
  bluetoothSettings: {
    isEnabled: true,
    devices: [],
    connectedDeviceClassic: null,
  },
  measurementSettings: {
    nazev: 1,
    etrs: {
      b: 0,
      l: 0,
      h: 0,
    },
    jtsk: {
      X: 0,
      Y: 0,
      Hbpv: 0,
    },
    coordPDOP: 0,
    coordAccuX: 0,
    coordAccuY: 0,
    coordAccuZ: 0,
    coordMeasuredTime: 0,
    sumCoordX: 0,
    sumCoordY: 0,
    sumCoordZ: 0,
    boolRtk: false,
    boolRaw: false,
    formattedTime: '00:00:00',
    startTime: null,
    endTime: null,
    intervalRawMeasurement: 0,
  },
  placingSettings: {
    points: null,
    selectedPoint: 0,
    dist: 0,
    heading: 0,
    heightDelta: 0,
  },
  nmeaRead: [],
  rtcmNtrip: [],
  lastGGA: '',
}